### ! CREWS

### Get all user's crews
GET http://localhost:3000/user/1/crews

### Get one user's crew
GET http://localhost:3000/user/1/crews/1

### ! Invited_user / user / users_in_crew / members :: fix wording everywhere
### ! also fix property names
### Post user crew
POST http://localhost:3000/user/1/crews/
content-type: application/json

{
    "crew_name":"testcrew232Ess",
    "crew_picture":"",
    "added_friends":[1,2,3,4]
}

### Update a crew
PATCH http://localhost:3000/user/1/crews/1
content-type: application/json

{
    "userId": 1,
    "crewId": 1,
    "picture": "ezzz",
    "name":"NewTeddddddddddddstCrew",
    "membersId":[1,2]
}

### Delete user crew
DELETE http://localhost:3000/user/1/crews/
content-type: application/json

{
    "userId":1,
    "crew_id_param":13
}