### ! EVENTS

### ! param wording unconsistent
### Get all user's events
GET http://localhost:3000/user/2/events

### Get one user's event
GET http://localhost:3000/user/2/events/27

### !! Ajouter icone d'event !

### Post user event
POST http://localhost:3000/user/2/events/
content-type: application/json

{
    "theme": "Cinema",
    "date": "2024-02-20",
    "time": "17:00:00",
    "place": "UGC Ciné Cité",
    "picture": "ticket",
    "invited_users_ids": [],
    "invited_crews_ids": [2]
}

### Patch one event
PATCH http://localhost:3000/user/1/events/3
content-type: application/json

{
    "userId": 1,
    "eventId": 3,
    "date":"2024-01-02",
    "theme": "New TheDJImedz",
    "userIds": [1,2]
}

### Delete user event
DELETE http://localhost:3000/user/1/events
content-type: application/json

{
    "userId": 1,
    "eventId": 3
}

### Update state user event
PATCH http://localhost:3000/user/2/confirm/1
content-type: application/json

{
    "userId": 2,
    "eventId": 1,
    "state": true
}

### Get all user's events UNCONFIRMED
GET http://localhost:3000/user/2/unconfirmed
