### ! USERS

### Get all users
GET http://localhost:3000/user

### Get one user
GET http://localhost:3000/user/8

### Post user
POST http://localhost:3000/user 
content-type: application/json

{
    "nickname":"testingthesky",
    "firstname":"httpcreateduser1_firstname",
    "lastname":"httpcreateduser1_lasttname",
    "device":"httpcreateduser1_device",
    "picture":"httpcreateduser1_picture",
    "role":"member"
}

### Patch one user
PATCH http://localhost:3000/user/1
content-type: application/json

{
    "id": 1,
    "nickname":"22",
    "firstname":"222",
    "lastname":"22",
    "device": "dzdzdz",
    "picture": "ooo"
}
#### ! ca marche pas vraiment, ca met a null, mais ca n'efface pas l'entrée
### Delete one user
DELETE http://localhost:3000/user/8
content-type: application/json

{
    "id": 8
}