-- DROP ALL EXISTING FUNCTION

DROP FUNCTION IF EXISTS web.get_all_users;
DROP FUNCTION IF EXISTS web.get_one_user;
DROP FUNCTION IF EXISTS web.insert_user;
DROP FUNCTION IF EXISTS web.update_user;
DROP FUNCTION IF EXISTS web.delete_user;